### ISSUE TITLE
Tolerant parser

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#67]
@ppalaga I tell me why tolerant parser is not supported yet.

Let's me explain my problem with ec4e. 

I have an `.editorconfig `file which is not well valid (there is a section which is not well closed). When I open any file, the apply config is done, I query the editorconfig properties for this file at https://github.com/angelozerr/ec4e/blob/master/org.eclipse.ec4e/src/main/java/org/eclipse/ec4e/internal/EditorConfigPreferenceStore.java#L61 and this code throw an error because th .editorconfig has one section which is not closed.

Before your refactoring, they exists a tolerant flag. I have 2 choices:

 * try/catch of call of `queryOptions`, but it means because of just a section which is not closeed, .editorconfig cannot be used.
 * `queryOptions` can manage tolerant behaviour.

**Comment by ppalaga** [comment]
The change happened here: https://github.com/ec4j/ec4j/commit/1cedd46f242da9cbd788cf4c07f965e19501112a and the commit message describes what changed and why.

To apply the above on your situation, you need to make the parser use ErrorHandler.IGNORING (or some custome impl.) rather than `Errorhandler.THROWING` that is used by default. You want to replace `this.loader = EditorConfigLoader.of(version, registry);` with a three arg variant `this.loader = EditorConfigLoader.of(version, registry, ErrorHandler.IGNORING);` on https://github.com/angelozerr/ec4e/blob/master/org.eclipse.ec4e/src/main/java/org/eclipse/ec4e/IDEEditorConfigManager.java#L137

**Comment by angelozerr** [comment]
Works like a charm, thanks @ppalaga !
